### PR TITLE
Convert to no-std

### PR DESCRIPTION
**Pull request by Greedeuh**
Hey :wave: 

Thanks for your work, I'm glab that I can use your lib.
My usage is in a `no-std` env so I need it to be `no-std` too.
It's a small change that you may want, feel free to merge.
(I can turn it into a `no-std` feature if you want to avoid unecessary deps.)

### CODE REVIEW

**Comment by flosse** [comment]
Tanks for contributing!
Adding a `no-std` feature would be great :+1: 

thx!

**Comment by Greedeuh** [comment]
Ok I'll update soon :)

**Comment by Greedeuh** [comment]
Hey @flosse, the `no-std` feature is ready :)

**Comment by markus-k** [comment]
Since I just came across this PR: The cargo documentation mentions specifically that you should *not* create a `no-std` feature, but rather a `std` feature that is enabled by default, and can be disabled to run in `no_std` environments: https://doc.rust-lang.org/cargo/reference/features.html#feature-unification

**Comment by flosse** [comment]
> The cargo documentation mentions specifically that you should _not_ create a `no-std` feature, but rather a `std` feature

@markus-k Thanks for that hint!
@Greedeuh would you mind to turn it around?

**Comment by Greedeuh** [comment]
Ah cool suggestion, yep sure :)

**Comment by Greedeuh** [comment]
Hey!
Sorry I took my time. But actually I don't know how to do this 😄.
Because here I need num_traits dependency to replace std. So num_traits is optional but I don't know how to enable it without using a feature 🤔 ?

Btw the documentation tell us to have 'additive' features so you can combine features but here it's a replacement of std so I don't know, what do you think ? @markus-k @flosse

**Comment by markus-k** [comment]
I think you actually have a point, this indeed doesn't seem to be possible: https://github.com/rust-lang/cargo/issues/1839

So I guess the options are:
1. stick to a `no-std` feature
2. ignore the fact that the crate depends on `num_traits` even though it's not used with `std`.
3. make use of the `num_traits` crate in either way by converting the entire crate to be generic over the kind of float used. Currently everything is `f64`, but that could be quite slow, especially on microcontrollers which usally don't have hardware support for 64bit floats. That might be out of scope for this PR though.

**Comment by Greedeuh** [comment]
Yep, I agree!
I'll let @flosse decide ;)

**Pull request closed without merging**
